In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
print(arr)

[1 2 3 4 5]


In [5]:
print(np.__version__)

1.18.5


In [6]:
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
arr = np.array((1,2,3,4,5))

In [8]:
print(arr)

[1 2 3 4 5]


In [9]:
arr0d = np.array(42)

In [10]:
print(arr0d)

42


In [12]:
arr1d= np.array([1,2,3,4,5])

In [13]:
print(arr1d)

[1 2 3 4 5]


In [14]:
arr2d = np.array([[1,2,3],[4,5,6]])

In [15]:
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [16]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [17]:
print(arr3d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [18]:
print(arr0d.ndim)

0


In [19]:
print(arr1d.ndim)

1


In [20]:
print(arr2d.ndim)

2


In [21]:
print(arr3d.ndim)

3


In [26]:
arr5d = np.array([1,2,3,4], ndim=5)

TypeError: 'ndim' is an invalid keyword argument for array()

In [27]:
arr5d = np.array([1,2,3,4], ndmin=5)

In [30]:
print(arr5d)

[[[[[1 2 3 4]]]]]


In [31]:
print(arr5d.ndim)

5


In [33]:
print(arr)

[1 2 3 4 5]


In [34]:
print(arr[0])

1


In [35]:
print(arr[2]+arr[3])

7


In [36]:
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [38]:
print(arr2d[0,2])

3


In [39]:
print(arr2d[1,1])

5


In [40]:
print(arr3d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [41]:
print(arr3d[0,0,1])

2


In [42]:
print(arr3d[0,1,1])

5


In [43]:
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [44]:
print(arr2d[1,-1])

6


In [45]:
print(arr2d[-2,-3])

1


In [46]:
arr = np.array([1,2,3,4,5,6,7])

In [47]:
print(arr[1:5])

[2 3 4 5]


In [48]:
print(arr[3:])

[4 5 6 7]


In [49]:
print(arr[:4])

[1 2 3 4]


In [50]:
print(arr[:3])

[1 2 3]


In [51]:
print(arr[-3:-1])

[5 6]


In [52]:
print(arr[1:5:2])

[2 4]


In [53]:
print(arr[::2])

[1 3 5 7]


In [55]:
print(arr[1::2])

[2 4 6]


In [56]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [57]:
print(arr[1, :3])

[6 7 8]


In [58]:
print(arr[:,2])

[3 8]


In [59]:
print(arr[:,1:4])

[[2 3 4]
 [7 8 9]]


In [60]:
arr = np.array([1,2,3,4,5])

In [61]:
print(arr.dtype)

int32


In [62]:
arr = np.array(["apple","banana","mango"])
print(arr.dtype)

<U6


In [63]:
arr = np.array([1,2,3,4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [64]:
arr = np.array([1,2,3,4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [65]:
arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

In [66]:
arr = np.array([1.1,2.1,3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [67]:
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [68]:
arr = np.array([1,0,3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [69]:
arr = np.array([23,464,121, 534])
x = arr.copy()
arr[0] = 12
print(arr)
print(x)

[ 12 464 121 534]
[ 23 464 121 534]


In [70]:
arr = np.array([23,464,121, 534])
x = arr.view()
arr[0] = 12
print(arr)
print(x)

[ 12 464 121 534]
[ 12 464 121 534]


In [71]:
arr = np.array([23,464,121, 534])
x = arr.view()
x[0] = 12
print(arr)
print(x)

[ 12 464 121 534]
[ 12 464 121 534]


In [72]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]
