In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

In [3]:
x = np.where(arr == 4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [4]:
x = np.where(arr%2==0)
print(x)

(array([1, 3, 5, 6], dtype=int64),)


In [5]:
x = np.where(arr%2==1)
print(x)

(array([0, 2, 4], dtype=int64),)


In [6]:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr,7)
print(x)

1


In [7]:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr,7, side="right")
print(x)

2


In [8]:
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2,3,6])
print(x)

[1 1 3]


In [9]:
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2,4,6])
print(x)

[1 2 3]


In [10]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [11]:
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [12]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr).base)

None


In [13]:
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


In [14]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [15]:
arr = np.array([41, 42, 43, 44])
x=np.array([True,False,True,False])
print(arr[x])

[41 43]


In [16]:
arr = np.array([41, 42, 43, 44])
filter_array = []
for ele in arr:
    if ele>42:
        filter_array.append(True)
    else: filter_array.append(False)
print(arr[filter_array])        

[43 44]


In [17]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_array = []
for ele in arr:
    if ele%2:
        filter_array.append(False)
    else: filter_array.append(True)
print(arr[filter_array])        

[2 4 6]


In [18]:
arr = np.array([41, 42, 43, 44])
filter_array = arr>42
print(arr[filter_array])

[43 44]


In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_array = arr%2 == 0
print(arr[filter_array])

[2 4 6]


In [21]:
from numpy import random

In [23]:
x= random.randint(100)
print(x)

89


In [24]:
x = random.rand()
print(x)

0.7134749073790193


In [26]:
x = random.randint(100, size=5)
print(x)

[85  1 92 74 47]


In [29]:
x= random.randint(100, size=(3,5))
print(x)

[[68  7 36 62 23]
 [60 94 33 18 88]
 [71 53 13 51 82]]


In [30]:
x= random.rand(5)
print(x)

[0.78155608 0.80583358 0.99410505 0.12518178 0.73267689]


In [32]:
x = random.rand(3,5)
print(x)

[[0.54844861 0.76671026 0.75092    0.22364005 0.2853901 ]
 [0.02786419 0.69263192 0.43252036 0.3834104  0.51063087]
 [0.4288146  0.47656334 0.558534   0.04315608 0.0162607 ]]


In [34]:
x = random.choice([3,5,7,9])
print(x)

7


In [35]:
x = random.choice([3,5,7,9], size=(3,5))
print(x)

[[5 7 9 9 9]
 [5 5 7 3 5]
 [5 7 7 5 7]]


In [37]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i,j in zip(x,y):
    z.append(i+j)
print(z)    

[5, 7, 9, 11]


In [39]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x,y)
print(z)

[ 5  7  9 11]


In [40]:
def myadd(x,y):
    return x+y
myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1,2,3,4],[4,5,6,7]))

[5 7 9 11]


In [41]:
print(type(np.add))

<class 'numpy.ufunc'>


In [42]:
print(type(np.concatenate))

<class 'function'>


In [43]:
if type(np.add) == np.ufunc:
    print('add is ufunc')
else:
    print('add is not ufunc')

add is ufunc


In [44]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

print(np.add(arr1,arr2))

[30 32 34 36 38 40]


In [45]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])
print(np.subtract(arr1,arr2))

[-10  -1   8  17  26  35]


In [46]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])
print(np.multiply(arr1,arr2))

[ 200  420  660  920 1200 1500]


In [47]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

print(np.divide(arr1, arr2))

[ 3.33333333  4.          3.          5.         25.          1.81818182]


In [48]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

print(np.power(arr1, arr2))

[      1000    3200000  729000000 -520093696       2500          0]


In [49]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

print(np.mod(arr1, arr2))

[ 1  6  3  0  0 27]


In [50]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

print(np.remainder(arr1, arr2))

[ 1  6  3  0  0 27]


In [51]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

print(np.divmod(arr1, arr2))

(array([ 3,  2,  3,  5, 25,  1], dtype=int32), array([ 1,  6,  3,  0,  0, 27], dtype=int32))


In [52]:
arr = np.array([-1, -2, 1, 2, 3, -4])
print(np.absolute(arr))

[1 2 1 2 3 4]


In [53]:
arr = np.trunc([-3.1666, 3.6667])

print(arr)

[-3.  3.]


In [54]:
arr = np.fix([-3.1666, 3.6667])

print(arr)

[-3.  3.]


In [55]:
arr = np.around(3.1666, 2)

print(arr)

3.17


In [56]:
arr = np.floor([-3.1666, 3.6667])

print(arr)

[-4.  3.]


In [57]:
arr = np.ceil([-3.1666, 3.6667])

print(arr)

[-3.  4.]


In [58]:
arr = np.arange(1, 10)

print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [59]:
arr = np.arange(1, 10)

print(np.log10(arr))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [60]:
arr = np.arange(1, 10)

print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [61]:
from math import log

nplog = np.frompyfunc(log, 2, 1)

print(nplog(100, 15))

1.7005483074552052


In [62]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.add(arr1, arr2)

print(newarr)

[2 4 6]


In [63]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2])

print(newarr)

12


In [64]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=1)

print(newarr)

[6 6]


In [65]:
arr = np.array([1, 2, 3])

newarr = np.cumsum(arr)

print(newarr)

[1 3 6]


In [66]:
arr = np.array([1, 2, 3, 4])

x = np.prod(arr)

print(x)

24


In [67]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

x = np.prod([arr1, arr2])

print(x)

40320


In [68]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

newarr = np.prod([arr1, arr2], axis=1)

print(newarr)

[  24 1680]


In [69]:
arr = np.array([5, 6, 7, 8])

newarr = np.cumprod(arr)

print(newarr)

[   5   30  210 1680]


In [70]:
arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr)

print(newarr)

[  5  10 -20]


In [71]:
arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr, n=2)

print(newarr)

[  5 -30]


In [72]:
num1 = 4
num2 = 6

x = np.lcm(num1, num2)

print(x)

12


In [73]:
arr = np.array([3, 6, 9])

x = np.lcm.reduce(arr)

print(x)

18


In [74]:
arr = np.arange(1, 11)

x = np.lcm.reduce(arr)

print(x)

2520


In [75]:
num1 = 6
num2 = 9

x = np.gcd(num1, num2)

print(x)

3


In [76]:
arr = np.array([20, 8, 32, 36, 16])

x = np.gcd.reduce(arr)

print(x)

4


In [77]:
x = np.sin(np.pi/2)

print(x)

1.0


In [78]:
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.sin(arr)

print(x)

[1.         0.8660254  0.70710678 0.58778525]


In [79]:
arr = np.array([90, 180, 270, 360])

x = np.deg2rad(arr)

print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


In [80]:
arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

x = np.rad2deg(arr)

print(x)

[ 90. 180. 270. 360.]


In [81]:
x = np.arcsin(1.0)

print(x)

1.5707963267948966


In [82]:
arr = np.array([1, -1, 0.1])

x = np.arcsin(arr)

print(x)

[ 1.57079633 -1.57079633  0.10016742]


In [83]:
base = 3
perp = 4

x = np.hypot(base, perp)

print(x)

5.0


In [84]:
x = np.sinh(np.pi/2)

print(x)

2.3012989023072947


In [85]:
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.cosh(arr)

print(x)

[2.50917848 1.60028686 1.32460909 1.20397209]


In [86]:
x = np.arcsinh(1.0)

print(x)

0.881373587019543


In [87]:
arr = np.array([0.1, 0.2, 0.5])

x = np.arctanh(arr)

print(x)

[0.10033535 0.20273255 0.54930614]


In [88]:
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)

[1 2 3 4 5 6 7]


In [89]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)

print(newarr)

[1 2 3 4 5 6]


In [90]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2, assume_unique=True)

print(newarr)

[3 4]


In [91]:
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set1, set2, assume_unique=True)

print(newarr)

[1 2]


In [92]:
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setxor1d(set1, set2, assume_unique=True)

print(newarr)

[1 2 5 6]
